import type { SupportedLocale } from "./i18n";

/** Minimal UI-chrome dictionary. Content itself comes from EmDash per-locale. */
const dict = {
	id: {
		searchPlaceholder: "Cari...",
		latest: "Terkini",
		viewAll: "Lihat semua",
		minRead: "mnt baca",
		emptyTitle: "Belum ada artikel",
		emptyBody: "Buat artikel pertama dari panel admin.",
		emptyCta: "Tulis artikel",
		navLabel: "Navigasi",
		connectedLabel: "Terhubung",
		themeLight: "Mode terang",
		themeDark: "Mode gelap",
		themeSystem: "Tema sistem",
		langLabel: "Language / Bahasa",
		minReadShort: "mnt",
		allArticles: "Semua Artikel",
		browseAll: "Jelajahi semua artikel",
		articleOne: "artikel",
		articleOther: "artikel",
		noArticles: "Belum ada artikel.",
		firstPage: "Halaman pertama",
		nextPage: "Halaman berikutnya",
		pagination: "Paginasi",
		categoryLabel: "Rubrik",
		inCategory: "Artikel rubrik",
		allInCategory: "Semua artikel dalam rubrik",
		noCategoryPosts: "Belum ada artikel dalam rubrik ini.",
		tagLabel: "Tag",
		withTag: "Artikel bertag",
		allWithTag: "Semua artikel bertag",
		noTagPosts: "Belum ada artikel dengan tag ini.",
		authorLabel: "Penulis",
		byAuthor: "Artikel oleh",
		allByAuthor: "Semua artikel yang ditulis oleh",
		noAuthorPosts: "Belum ada artikel dari penulis ini.",
		untitled: "Tanpa judul",
		publishedLabel: "Diterbitkan",
		readTimeLabel: "Waktu baca",
		continueReading: "Lanjut baca",
		tocLabel: "Daftar isi",
		onThisPage: "Di halaman ini",
		searchTitle: "Pencarian",
		searchInTitle: "Cari",
		searchDesc: "Cari artikel",
		searchButton: "Cari",
		searchPlaceholderFull: "Cari artikel...",
		noResultsFor: "Tidak ada hasil untuk",
		resultsFor: "hasil untuk",
		searchHint: "Masukkan kata kunci untuk mencari artikel.",
		notFoundTitle: "Halaman tidak ditemukan",
		notFoundBody: "Halaman yang Anda cari tidak ada.",
		backHome: "Kembali ke beranda",
	},
	en: {
		searchPlaceholder: "Search...",
		latest: "Latest",
		viewAll: "View all",
		minRead: "min read",
		emptyTitle: "No posts yet",
		emptyBody: "Create your first post from the admin panel.",
		emptyCta: "Write a post",
		navLabel: "Navigation",
		connectedLabel: "Connect",
		themeLight: "Light mode",
		themeDark: "Dark mode",
		themeSystem: "System theme",
		langLabel: "Language / Bahasa",
		minReadShort: "min",
		allArticles: "All posts",
		browseAll: "Browse all posts",
		articleOne: "post",
		articleOther: "posts",
		noArticles: "No posts yet.",
		firstPage: "First page",
		nextPage: "Next page",
		pagination: "Pagination",
		categoryLabel: "Category",
		inCategory: "Posts in category",
		allInCategory: "All posts in category",
		noCategoryPosts: "No posts in this category yet.",
		tagLabel: "Tag",
		withTag: "Posts tagged",
		allWithTag: "All posts tagged",
		noTagPosts: "No posts with this tag yet.",
		authorLabel: "Author",
		byAuthor: "Posts by",
		allByAuthor: "All posts written by",
		noAuthorPosts: "No posts by this author yet.",
		untitled: "Untitled",
		publishedLabel: "Published",
		readTimeLabel: "Reading time",
		continueReading: "Continue reading",
		tocLabel: "Table of contents",
		onThisPage: "On this page",
		searchTitle: "Search",
		searchInTitle: "Search",
		searchDesc: "Search posts",
		searchButton: "Search",
		searchPlaceholderFull: "Search posts...",
		noResultsFor: "No results for",
		resultsFor: "results for",
		searchHint: "Enter keywords to search posts.",
		notFoundTitle: "Page not found",
		notFoundBody: "The page you're looking for doesn't exist.",
		backHome: "Back to home",
	},
} as const;

export type DictKey = keyof (typeof dict)["id"];

export function t(locale: SupportedLocale, key: DictKey): string {
	return dict[locale][key];
}
